# Generated by Django 4.0.4 on 2022-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('DOB', models.DateTimeField()),
                ('EmailId', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('FlatNo', models.CharField(max_length=250)),
                ('Street', models.CharField(max_length=250)),
                ('Country', models.CharField(choices=[('India', 'India'), ('Usa', 'Usa'), ('England', 'England')], default='India', max_length=100)),
                ('PhotoUpload', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Registration_Table',
            },
        ),
    ]
